services:
    redis-master:
      container_name: "redis-master"
      image: redis
      ports:
        - "6379:6379"
      command: "redis-server"

    redis-slave1:
      container_name: "redis-slave1"
      image: redis
      ports:
        - "6380:6380"
      command: "redis-server --port 6380 --replicaof redis-master 6379"
    
    redis-slave2:
      container_name: "redis-slave2"
      image: redis
      ports:
        - "6381:6381"
      command: "redis-server --port 6381 --replicaof redis-master 6379"
    
    redis-sentinel1:
      container_name: "redis-sentinel1"
      image: redis
      ports:
        - "5500:5500"
      command: "redis-server /etc/Sentinel/sentinel1.conf --sentinel"
      volumes:
        - "./Config/Sentinel1:/etc/Sentinel"
        - "./data/sentinel1/:/data/"
      depends_on:
        - redis-master
      
    redis-sentinel2:
      container_name: "redis-sentinel2"
      image: redis
      ports:
        - "5600:5600"
      command: "redis-server /etc/Sentinel/sentinel2.conf --sentinel"
      volumes:
        - "./Config/Sentinel2:/etc/Sentinel"
        - "./data/sentinel2/:/data/"
      depends_on:
        - redis-master

    redis-sentinel3:
      container_name: "redis-sentinel3"
      image: redis
      ports:
        - "5700:5700"
      command: "redis-server /etc/Sentinel/sentinel3.conf --sentinel"
      volumes:
        - "./Config/sentinel3:/etc/Sentinel"
        - "./data/sentinel3/:/data/"
      depends_on:
        - redis-master