services:
    redis-master:
      container_name: "redis-master"
      image: redis
      ports:
        - "6379:6379"
      command: "redis-server"

    redis-slave1:
      container_name: "redis-slave1"
      image: redis
      ports:
        - "6380:6380"
      command: "redis-server --port 6380 --replicaof redis-master 6379"
    
    redis-slave2:
      container_name: "redis-slave2"
      image: redis
      ports:
        - "6381:6381"
      command: "redis-server --port 6381 --replicaof redis-master 6379"