services:

    redis-sentinel:
      container_name: "redis-sentinel"
      image: redis
      ports:
        - "5500:5500"
      command: "redis-server /etc/sentinel.conf --sentinel"
      volumes:
        - "./Config/1:/etc"
        - "./data/sentinel1/:/data/"
      depends_on:
        - redis-master

    redis-sentinel1:
      container_name: "redis-sentinel1"
      image: redis
      ports:
        - "5600:5600"
      command: "redis-server /etc/sentinel1.conf --sentinel"
      volumes:
        - "./Config/2:/etc"
        - "./data/sentinel2/:/data/"
      depends_on:
        - redis-master

    redis-sentinel2:
      container_name: "redis-sentinel2"
      image: redis
      ports:
        - "5700:5700"
      command: "redis-server /etc/sentinel2.conf --sentinel"
      volumes:
        - "./Config/3:/etc"
        - "./data/sentinel3/:/data/"
      depends_on:
        - redis-master